name: brew test-bot

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: test-bot-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  test-bot:
    runs-on: xcode-27
    timeout-minutes: 60
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    env:
      DEVELOPER_DIR: /Applications/Xcode_27.app/Contents/Developer
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@e99025eb970cfa124b8284a35463d87426917478 # 2026.09.28.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: xcode-27-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: xcode-27-rubygems-

      - name: Check toolchain
        run: swift --version

      - name: Clean up test environment
        run: brew test-bot --only-cleanup-before

      - name: Check Homebrew setup
        run: brew test-bot --only-setup

      - name: Check tap syntax
        run: brew test-bot --only-tap-syntax

      - name: Build and test changed formulae
        if: github.event_name == 'pull_request'
        run: brew test-bot --only-formulae

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: bottles_xcode-27
          path: '*.bottle.*'
          if-no-files-found: ignore
